---
title: "About"
date: 2026-08-28
citation:
  type: "webpage"
  title: "Educational resources for teaching open research to novices"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/teaching-material-for-novices/
  version: 0.0.1
author:
  - name: Sarah von Grebmer zu Wolfsthurn
    affiliation:
      - id: osc
        name: LMU Open Science Center, Ludwig-Maximilians-Universität München
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-6413-3895
  - name: Sara Middleton
    affiliation:
      - id: osc
    orcid: 0000-0001-5307-8029
  - name: Malika Ihle
    affiliation:
      - id: osc
    orcid: 0000-0002-3242-5981
  - name: Felix Schönbrodt
    affiliation:
      - id: osc
    orcid: 0000-0002-8282-3910
  - name: Peter Edelsbrunner
    affiliation:
      - id: osc
    orcid: 0000-0001-9102-1090
  - name: Elizabeth Waterfield
    affiliation:
      - id: osc
    orcid: 0009-0006-3725-6730
  - name: David Rieger
    affiliation:
      - id: osc
    orcid: 0009-0004-3701-3101
  - name: Tejaswini Sharma
    affiliation:
      - id: osc
    orcid: 0009-0000-0305-9751
  - name: Caterina Luz Sanchez Steinhagen
    affiliation:
      - id: osc
    orcid: 0009-0006-4783-1110
google-scholar: true
---

## Contributors

These materials were authored by Sarah von Grebmer zu Wolfsthurn, Sara Middleton, Malika Ihle, Felix Schönbrodt, Peter Edelsbrunner, Elizabeth Waterfield, David Rieger, Tejaswini Sharma, and Caterina Luz Sanchez Steinhagen. Edits and further contributions were made by the LMU Open Science Center team and the FORRT community. See the [home page](index.qmd) for the full list of contributors and their ORCID iDs.

## Licenses

The overall project is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the [**CC0 1.0 Universal**](https://creativecommons.org/publicdomain/zero/1.0/) license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

## Notes

These teaching materials were primarily written in 2026 using Quarto. Major changes to Quarto can be found at the [Quarto website](https://quarto.org/) for the most up-to-date information, and to confirm that these materials are not out-of-date.

## Tutorial Template Quarto Extension

This site was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

::: {#refs}
:::

## How to Cite

**To cite these materials, please refer to the project's [CITATION.cff](CITATION.cff) file or use the BibTeX citation provided in the appendix below.**
