---
title: "Educational resources for teaching open research to novices"
---

## Welcome!

Are you interested in **conveying foundational open research knowledge and skills** in the context of an open research course? Are you looking for **teaching materials on a specific open research topic** to use in **your own teaching**? Or are you **new to open research** as a whole and are trying **acquire and practice some open research skills** by yourself? **Then you are in the right place**!

On this page you will find **ready-to-use materials** and educational resources for **teaching open research practices** to novices or students on topics including **foundations of Open Science, computational reproducibility, tools for collaborative working, data management and data sharing** in a **synchronous class-room setting** (in-person, virtual or hybrid) or to use offline to learn at your own pace.

## Who are these materials for?

**Educators** in higher higher education (e.g., universities, colleges, research institutions), looking for **materials to teach a full course** on open research or **delivering individual workshops** on specific open research topics to audiences with **no or limited prior experience** with open research, aiming to:

- **Integrate** open research into an existing course syllabus or **develop and deliver** a full open research course
- **Develop** a basic understanding of core principles in open research in their learners
- **Equip** learners with foundational skills and experience with open research practices

**Self-learners** with no prior experience in open research, aiming to:

- **Develop** basic open research skills
- **Obtain** hands-on practical experience with core open research practices
- **Build-up** on existing open research skills

## What materials are there?

The materials consist of **slide decks** with **theoretical elements**, **hands-on exercises**, **cheatsheets**, **homework assignments** and **practical tips** on the content. 

Each slide deck on a given topic is **designed for a 90-minute session** in a classroom setting (in-person, virtual, or hybrid), and can be **flexibly adapted** depending on your audience and timeframe. 

Detailed **presenter notes** (intended narrative of the presentation), further **instructor notes** (additional guidance intended only for the presenter) and **accessibility tips** (where applicable) are available for each topic and are directly integrated into the materials.

The materials are completely **free to use**, given that you give appropriate credit.

::: {.callout-tip collapse="false"}
## Adapting the materials
**You want to adapt the materials for your audience**? The source code for the materials as well as PowerPoint files are available for download to tailor the materials to your exact audience.
:::

## How can I use these materials?

**As an educator aiming to teach about open research**: The materials are ready for immediate use in a classroom setting (timeframe: approx. 90 minutes per topic). You can choose to **deliver a full course** with the existing materials, *or* you can **pick-and-choose specific open research topics** to incorporate into an existing course. To access to materials, use the navigation menu on the left. The materials are arranged in a **chronological order**, meaning that they logically build up on one another. The slides can be directly presented in the browser in full screen or can be downloaded as pdf or MS PowerPoint if you want to **edit** them or present the materials offline. **Presenter notes**, **instructor notes** and **accessibility tips** provide important information about the content of the materials and valuable pedagogical tips how to convey the materials to your audience. If you opt for the pick-and-choose option, make sure to thoroughly **read the prerequisites** for each topic and **go through the content and exercises yourself**. If you re-use the materials for your own teaching, make sure to give appropriate credit to the original authors.

**As a self-learner**: Select your **topic of choice** from the navigation menu on the left. Follow along the slides and **complete the practical exercises** in your own time. You can navigate the slides in full screen using the arrow key, or by viewing the slides in the *Speaker View* together with the **presenter and instructor notes** to understand and reflect on the content of the materials (recommended, see [here](https://quarto.org/docs/presentations/revealjs/presenting.html) for more information). Make sure to always **familiarize** yourself with the **prerequisites** before starting a new topic. The materials can be downloaded as pdf or MS PowerPoint documents. *Note*: Group exercises are not possible in an asynchronous setting, but can be completed individually.

::: {.callout-important collapse="false"}
## Read the introductory page for each topic
When selecting a topic, you will be redirected to a separate website with all the materials. Please ensure to **read** the **About these materials** section, as well as details about the **intended target audience**, the **prerequisites** to complete the topic and the **learning objectives**. You can also find the contributor list, the license details and the citation statement on each website.
:::

## Getting started

When you click the following button, it takes you directly to the first topic. Enjoy!

<a href="open-research-principles/reproducibility-replicability/index.html" target="_blank" 
   style="display:inline-block;
          padding:12px 20px;
          background-color:#009933;
          color:white;
          text-decoration:none;
          border-radius:8px;
          font-weight:bold;">
  Start here!
</a>

## How can I adapt the materials?

Of course, the context in which you are teaching may vary greatly and you may need to **adapt the materials** in terms of your audience, content, level of difficulty or timeframe. If you **want to adapt the materials**, you can **export the slides as MS PowerPoint** (.pptx format) corresponding to the materials and adapt the materials to your specific teaching context. Make sure to give appropriate credit to the original authors. You also have the option to **export the slides in pdf format**. 

In addition, you can also obtain the materials from our [LMU OSC GitHub repository](https://lmu-osc.github.io/train-the-trainer-student-track-OS/). You can [clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) and [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) the repository to adapt the materials to your needs, or [create a new branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) to work on the materials in parallel. Within this repository, you have direct access to the **Quarto .qmd files** that support all of our materials. 

## How can I give feedback on the materials?

Have you spotted a **way to improve our materials**, or would like to add or **contribute** to the materials? **We would love to hear your feedback!** There are different ways to give feedback:

- **The quick and easy way**: Contact the program coordinator [Sarah von Grebmer](mailto:s.grebmer@lmu.de).

- **The pro way** (involves GitHub): Navigate to the GitHub repository and open an issue, see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue) for instructions on how to do this. Provide a descriptive title for your feedback, and describe your feedback in greater detail in the text box. Include which materials you want to provide feedback on, what the issue is and if it is low, medium or high priority. Tag Sarah von Grebmer (using her GitHub username [SvonGrebmer](https://github.com/SvonGrebmer)).

## Frequently asked questions

1. **What previous knowledge do I need about open research to teach with those slides?**

  - No prior open research knowledge is required! You can first acquire the open research skills yourself by going through the slides and practical activities, or you can also complete the self-paced tutorials on these topics in the [self learning catalogue](https://lmu-osc.github.io/training/self-learning.html). In addition, you can [develop your teaching skills here](https://lmu-osc.github.io/train-the-trainer-open-research/). 
  
2. **Who can I teach with these materials?**

  - The materials can be flexibly adapted to bachelor students, master students or early career researchers (PhD, PostDocs) who are new to open research or have not had prior training on these topics.

3. **I am not a member of the LMU Open Science Center, can I still teach with these slides?**

  - Yes! Just make sure to give the appropriate credit and honor the licence conditions while teaching (this also applies to LMU-based educators!). If you are based at LMU, consider [joining the LMU Open Science Center](https://lmu-osc.github.io/about/join-us.html) to support the goal of open, responsible, and reproducible research within your disciplines or at LMU Munich more broadly.

::: {.callout-note}
## Cannot find the answer you are looking for?
Please get in touch with the program coordinator [Sarah von Grebmer](mailto:s.grebmer@lmu.de).
:::

## Licence and citation statement

::: {.callout-tip}
## How to cite these materials while they are work in progress
Von Grebmer Zu Wolfsthurn, S., Middleton S.,Ihle, M., & Schönbrodt, F. (2026). *Educational resources for teaching open research to novices*. LMU Open Science Center. Retrieved September 28, 2026, from [https://github.com/lmu-osc/teaching-material-for-novices](https://github.com/lmu-osc/teaching-material-for-novices)
:::

Unless otherwise specified, the text, images and supplementary materials on these pages is licenced under a [Creative Commons Attribution 4.0 International SA License](https://creativecommons.org/licenses/by-sa/4.0/deed.en) (**CC-BY-SA-4.0**). Note that code embedded in these materials is licensed under a [Creative Commons 0 Public Domain License](https://creativecommons.org/public-domain/cc0/) (**CC0 1.0**).

## List of current contributors

- Sarah von Grebmer zu Wolfsthurn, [ORCID 0000-0002-6413-3895](https://orcid.org/0000-0002-6413-3895), LMU Open Science Center

- Sara Middleton, [ORCID 0000-0001-5307-8029](https://orcid.org/0000-0001-5307-8029), LMU Open Science Center

- Malika Ihle, [ORCID 0000-0002-3242-5981](https://orcid.org/0000-0002-3242-5981), LMU Open Science Center

- Felix Schönbrodt, [ORCID 0000-0002-8282-3910](https://orcid.org/0000-0002-8282-3910), LMU Open Science Center and Ludwig-Maximilians-Universität München, Faculty of Psychology and Pedagogy

- Peter Edelsbrunner, [ORCID 0000-0001-9102-1090](https://orcid.org/0000-0001-9102-1090), Ludwig-Maximilians-Universität München, Faculty of Psychology and Pedagogy

- Elizabeth Waterfield, [ORCID 0009-0006-3725-6730](https://orcid.org/0009-0006-3725-6730), LMU Open Science Center

- David Rieger, [ORCID 0009-0004-3701-3101](https://orcid.org/0009-0004-3701-3101), LMU Open Science Center

- Tejaswini Sharma, [ORCID 0009-0000-0305-9751](https://orcid.org/0009-0000-0305-9751), LMU Open Science Center

- Caterina Luz Sanchez Steinhagen [ORCID 0009-0006-4783-1110](https://orcid.org/0009-0006-4783-1110), LMU Open Science Center

## Funding and partners

This project is funded by the [VolksWagen Foundation](https://www.volkswagenstiftung.de/de) and is developed in collaboration with [FORRT](https://forrt.org/).

:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like these materials? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}

::: {.callout-tip title="Questions about these materials?"}
**If you have questions for the authors of these materials, please take a look at the [About](about.qmd) page.**
:::

:::

::::

